Final: Source1.o Source2.o Source3.o
	gcc -o Final Source1.o Source2.o Source3.o

Source1.o: Proj4-Source1.c Proj4-Header.h
	gcc -c Proj4-Source1.c

Source2.o: Proj4-Source2.c Proj4-Header.h
	gcc -c Proj4-Source2.c

Source3.o: Proj4-Source3.c Proj4-Header.h
	gcc -c Proj4-Source3.c

clean:
	rm -rf *o Final
